_wandb:
    value:
        cli_version: 0.23.0
        e:
            8xgq7r281mlvq1wgj4plx5gwxzyqf9qm:
                args:
                    - attacks.attack_norm=linf
                    - attacks.attack_eps=0.0
                    - attacks.advtrain=false
                    - attacks.gradnorm=false
                    - model.experiment_num=2
                    - model.resume=/home/ashtomer/projects/ares/results/sweep_mixup_light/last.pth.tar
                    - training.epochs=250
                    - training.batch_size=512
                    - optimizer.clip_grad=1
                    - dataset.mixup=0.2
                    - dataset.cutmix=0.0
                    - output_dir=/home/ashtomer/projects/ares/results/sweep_mixup_light
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "861060038656"
                        used: "13832880128"
                email: ashtomer@post.bgu.ac.il
                executable: /home/ashtomer/.conda/envs/tomer_advtrain_pro/bin/python
                git:
                    commit: e2e5888fd4df709257952c2ef198aeba85b7f1d3
                    remote: https://github.com/brainsandmachines/ares2.0.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-d7a930b2-d1f8-f6fd-e796-41816c9d9fe5
                host: ise-6000p-01.auth.ad.bgu.ac.il
                memory:
                    total: "540332716032"
                os: Linux-5.14.0-570.55.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: -m robust_training.hydra_advtrain
                python: CPython 3.11.14
                root: /home/ashtomer/projects/ares
                slurm:
                    array_job_id: "8254941"
                    array_task_count: "200"
                    array_task_id: "21"
                    array_task_max: "200"
                    array_task_min: "1"
                    array_task_step: "1"
                    cluster_name: cluster
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "12"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: golan.neuro
                    job_cpus_per_node: "12"
                    job_end_time: "1764677415"
                    job_gid: "1945600513"
                    job_gpus: "4"
                    job_id: "8331140"
                    job_name: convnext_small_training
                    job_nodelist: ise-6000p-01
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1764072615"
                    job_uid: "343900539"
                    job_user: ashtomer
                    jobid: "8331140"
                    localid: "0"
                    mem_per_node: "98304"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: ise-6000p-01
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /home/ashtomer
                    submit_host: slurm-login-01
                    task_pid: "1984890"
                    tasks_per_node: "1"
                    topology_addr: ise-6000p-01
                    topology_addr_pattern: node
                startedAt: "2025-11-25T12:12:38.745591Z"
                writerId: 8xgq7r281mlvq1wgj4plx5gwxzyqf9qm
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 41
                - 49
                - 50
                - 63
            "2":
                - 1
                - 41
                - 49
                - 50
                - 63
            "3":
                - 5
                - 13
                - 14
                - 16
                - 62
            "4": 3.11.14
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
aa:
    value: null
advprop:
    value: false
advtrain:
    value: false
amp_version:
    value: native
apex_amp:
    value: false
attack_criterion:
    value: mixup
attack_eps:
    value: 0
attack_it:
    value: 3
attack_norm:
    value: linf
attack_step:
    value: 0.00392156862745098
aug_repeats:
    value: 0
aug_splits:
    value: 0
backend:
    value: nccl
batch_size:
    value: 512
bce_loss:
    value: false
bn_eps:
    value: null
bn_momentum:
    value: null
channels_last:
    value: false
clip_grad:
    value: 1
clip_mode:
    value: norm
color_jitter:
    value: 0
cooldown_epochs:
    value: 0
crop_pct:
    value: 0.875
cutmix:
    value: 0
cutmix_minmax:
    value: null
decay_epochs:
    value: 30
decay_rate:
    value: 0.1
device_id:
    value: 0
dist_backend:
    value: nccl
dist_bn:
    value: reduce
dist_url:
    value: env://
distributed:
    value: false
drop:
    value: 0
drop_block:
    value: null
drop_path:
    value: 0
epoch_repeats:
    value: 0
epochs:
    value: 250
eval_dir:
    value: /storage/test/bml_group/tomerash/datasets/imagenet/val/
eval_metric:
    value: top1
experiment_name:
    value: null
experiment_num:
    value: 2
gp:
    value: null
gradnorm:
    value: false
hflip:
    value: true
init_method:
    value: env://
input_size:
    value: 224
interpolation:
    value: bicubic
jsd_loss:
    value: false
lambda_ce:
    value: 0.8
lambda_gn:
    value: 1.2
layer_decay:
    value: null
local_rank:
    value: 0
log_interval:
    value: 50
lr:
    value: 0.001
lr_cycle_decay:
    value: 0.5
lr_cycle_limit:
    value: 1
lr_cycle_mul:
    value: 1
lr_k_decay:
    value: 1
lr_noise:
    value: null
lr_noise_pct:
    value: 0.67
lr_noise_std:
    value: 1
lrb:
    value: 0.001
max_history:
    value: 10
mean:
    value:
        - 0.485
        - 0.456
        - 0.406
min_lr:
    value: 1e-05
mixup:
    value: 0.2
mixup_active:
    value: true
mixup_mode:
    value: elem
mixup_off_epoch:
    value: 200
mixup_prob:
    value: 0.5
mixup_switch_prob:
    value: 0.5
model:
    value: convnext_small
model_ema:
    value: true
model_ema_decay:
    value: 0.9998
model_ema_force_cpu:
    value: false
model_id:
    value: null
momentum:
    value: 0.9
native_amp:
    value: true
no_aug:
    value: false
num_classes:
    value: 1000
num_workers:
    value: 6
opt:
    value: adamw
opt_betas:
    value: null
opt_eps:
    value: 1e-08
output_dir:
    value: /home/ashtomer/projects/ares/results/sweep_mixup_light/convnext_small_init2
patience_epochs:
    value: 0
pin_mem:
    value: true
rank:
    value: 0
ratio:
    value:
        - 0.75
        - 1.3333
recount:
    value: 1
recovery_interval:
    value: 0
remode:
    value: pixel
reprob:
    value: 0.25
resplit:
    value: false
resume:
    value: /home/ashtomer/projects/ares/results/sweep_mixup_light/last.pth.tar
save_log:
    value: save_log.txt
scale:
    value:
        - 0.08
        - 1
sched:
    value: cosine
sched_on_updates:
    value: true
seed:
    value: 0
smoothing:
    value: 0.1
split_bn:
    value: false
start_epoch:
    value: null
std:
    value:
        - 0.229
        - 0.224
        - 0.225
sync_bn:
    value: false
train_dir:
    value: /storage/test/bml_group/tomerash/datasets/imagenet/train/
train_interpolation:
    value: bicubic
vflip:
    value: false
warmup_epochs:
    value: 20
warmup_lr:
    value: 1e-06
weight_decay:
    value: 0.05
world_size:
    value: 1
