_wandb:
    value:
        cli_version: 0.23.0
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 41
                - 49
                - 50
                - 63
                - 82
            "3":
                - 13
                - 14
                - 16
            "4": 3.11.14
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
aa:
    value: null
advprop:
    value: false
advtrain:
    value: true
amp_version:
    value: native
apex_amp:
    value: false
attack_criterion:
    value: mixup
attack_eps:
    value: 0.0196078431372549
attack_it:
    value: 3
attack_norm:
    value: linf
attack_step:
    value: 0.00392156862745098
aug_repeats:
    value: 0
aug_splits:
    value: 0
backend:
    value: nccl
batch_size:
    value: 256
bce_loss:
    value: false
bn_eps:
    value: null
bn_momentum:
    value: null
channels_last:
    value: false
clip_grad:
    value: null
clip_mode:
    value: norm
color_jitter:
    value: 0
cooldown_epochs:
    value: 0
crop_pct:
    value: 0.875
cutmix:
    value: 1
cutmix_minmax:
    value: null
decay_epochs:
    value: 30
decay_rate:
    value: 0.1
device_id:
    value: 0
dist_backend:
    value: nccl
dist_bn:
    value: reduce
dist_url:
    value: env://
distributed:
    value: false
drop:
    value: 0
drop_block:
    value: null
drop_path:
    value: 0
epoch_repeats:
    value: 0
epochs:
    value: 250
eval_dir:
    value: /storage/test/bml_group/tomerash/datasets/imagenet_sample/val/
eval_metric:
    value: top1
experiment_name:
    value: null
experiment_num:
    value: 1
gp:
    value: null
gradnorm:
    value: true
hflip:
    value: true
init_method:
    value: env://
input_size:
    value: 224
interpolation:
    value: bicubic
jsd_loss:
    value: false
lambda_ce:
    value: 0.8
lambda_gn:
    value: 1.2
layer_decay:
    value: null
local_rank:
    value: 0
log_interval:
    value: 50
lr:
    value: 5e-05
lr_cycle_decay:
    value: 0.5
lr_cycle_limit:
    value: 1
lr_cycle_mul:
    value: 1
lr_k_decay:
    value: 1
lr_noise:
    value: null
lr_noise_pct:
    value: 0.67
lr_noise_std:
    value: 1
lrb:
    value: 0.0001
max_history:
    value: 10
mean:
    value:
        - 0.485
        - 0.456
        - 0.406
min_lr:
    value: 1e-05
mixup:
    value: 0.8
mixup_mode:
    value: batch
mixup_off_epoch:
    value: 200
mixup_prob:
    value: 1e-06
mixup_switch_prob:
    value: 0.5
model:
    value: convnext_small
model_ema:
    value: true
model_ema_decay:
    value: 0.9998
model_ema_force_cpu:
    value: false
model_id:
    value: null
momentum:
    value: 0.9
native_amp:
    value: true
no_aug:
    value: false
num_classes:
    value: 1000
num_workers:
    value: 6
opt:
    value: adamw
opt_betas:
    value: null
opt_eps:
    value: 1e-08
output_dir:
    value: /home/ashtomer/projects/ares/results/convnext_small_linf_0.0196078431372549_gradnorm_0.0196078431372549_init1
patience_epochs:
    value: 0
pin_mem:
    value: true
rank:
    value: 0
ratio:
    value:
        - 0.75
        - 1.3333
recount:
    value: 1
recovery_interval:
    value: 0
remode:
    value: pixel
reprob:
    value: 0
resplit:
    value: false
resume:
    value: /home/ashtomer/projects/ares/results/last.pth.tar
save_log:
    value: save_log.txt
scale:
    value:
        - 0.08
        - 1
sched:
    value: cosine
sched_on_updates:
    value: true
seed:
    value: 0
smoothing:
    value: 0.1
split_bn:
    value: false
start_epoch:
    value: null
std:
    value:
        - 0.229
        - 0.224
        - 0.225
sync_bn:
    value: false
train_dir:
    value: /storage/test/bml_group/tomerash/datasets/imagenet_sample/train/
train_interpolation:
    value: bicubic
vflip:
    value: false
warmup_epochs:
    value: 10
warmup_lr:
    value: 1e-06
weight_decay:
    value: 0.05
world_size:
    value: 1
