# Main Hydra config. It composes the specific group configs below.
defaults:
  - lr_scheduler: cosine
  - model: convnext_small
  - dataset: imagenet
  - optimizer: adamw
  - attacks: adv
  - dist: default
  - training: convnext_small
  - _self_


# Training / schedule / augmentation / misc settings split from convnext_small.yaml
# amp parameters
apex_amp: False
native_amp: True

# misc
seed: 0
log_interval: 50
recovery_interval: 0
num_workers: 6
output_dir: 'results/models'
save_log: save_log.txt
eval_metric: top1
pin_mem: True
