# Dataset settings for ImageNet
train_dir: '/storage/test/bml_group/tomerash/datasets/imagenet/train/'
eval_dir: '/storage/test/bml_group/tomerash/datasets/imagenet/val/'
grad_accum: 1
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
scale: [0.08, 1.0]
ratio: [0.75, 1.3333]
hflip: True
vflip: False

# augmentation
no_aug: False
color_jitter: 0
aa: rand-m9-mstd0.5-inc1
aug_repeats: 0
aug_splits: 0
jsd_loss: False
reprob: 0
remode: pixel
recount: 1
resplit: False

input_size: 224
crop_pct: 0.875
interpolation: bicubic
train_interpolation: bicubic

mixup_active: true
mixup: 0.8
cutmix: 1.0
cutmix_minmax: null
mixup_prob: 0.5
mixup_switch_prob: 0.5
mixup_mode: elem
mixup_off_epoch: 175
smoothing: 0.1
