# Adversarial / attack related defaults
advtrain: False
attack_criterion: madryv # madry / trades
attack_norm: linf # l2 / linf / l1
advprop: False
attack_eps: 0.0
attack_step: 1.0
attack_it: 3
bce_loss: False

random_start: False
random_start_eps_factor: 0.5

# TRADES related defaults
trades_beta: 1.0


# GradNorm related defaults
gradnorm: False
loss_fn: 'DBP'
ce_weight: 0.8
gradnorm_weight: 1.2
alpha: [0.0, 0.2, 1.0]
alpha_start_epoch: 0